services:
  tracker:
    build: .
    command: tracker
    ports:
      - "8080:8080"
    networks:
      - p2p-net

  seeder:
    build: .
    command: client /shared/small.txt.meta
    networks:
      - p2p-net
    expose:
      - "50000-50100" 
    depends_on:
      - tracker
    volumes:
      - ./shared:/shared
      - ./seeder-files:/downloads

  leecher1:
    build: .
    command: client /shared/small.txt.meta
    networks:
      - p2p-net
    expose:
      - "50000-50100"
    depends_on:
      - tracker
    volumes:
      - ./shared:/shared
      - leecher1-data:/downloads

  leecher2:
    build: .
    command: client /shared/small.txt.meta
    networks:
      - p2p-net
    expose:
      - "50000-50100"
    depends_on:
      - tracker
    volumes:
      - ./shared:/shared
      - leecher2-data:/downloads

networks:
  p2p-net:

volumes:
  leecher1-data:
  leecher2-data: